# See https://github.com/parcel-bundler/parcel/issues/7880
packageExtensions:
  "@parcel/cache@2.4.1":
    dependencies:
      "@parcel/core": 2.4.1
  "@parcel/fs@2.4.1":
    dependencies:
      "@parcel/core": 2.4.1
  "@parcel/package-manager@2.4.1":
    dependencies:
      "@parcel/core": 2.4.1
  "@parcel/workers@2.4.1":
    dependencies:
      "@parcel/core": 2.4.1

yarnPath: .yarn/releases/yarn-3.2.0.cjs
