packages:
  - packages/*
catalog:
  "@fast-check/ava": ^2.0.2
  "@fortawesome/fontawesome-free": ^6.7.2
  "@parcel/packager-ts": 2.16.3
  "@parcel/transformer-sass": 2.16.3
  "@parcel/transformer-typescript-types": 2.16.3
  "@popperjs/core": ^2.11.8
  "@rollup/plugin-commonjs": ^28.0.3
  "@types/eslint": ^9.6.1
  "@types/node": ^22.15.18
  "@typescript-eslint/eslint-plugin": ^8.51.0
  "@typescript-eslint/parser": ^8.51.0
  ava: ^6.4.1
  bootstrap: ^5.3.6
  c8: ^10.1.3
  eslint: ^9.39.2
  eslint-config-love: ^140.0.0
  eslint-plugin-node: ^11.1.0
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-tsdoc: ^0.4.0
  fast-check: ^4.5.3
  fps-control: ^1.0.0
  gh-pages: ^6.3.0
  parcel: 2.16.3
  rollup: ^4.54.0
  # INFO: this library may stalemate till ts7 is out.
  tsimp: ^2.0.12
  typedoc: ^0.28.15
  typedoc-plugin-mdn-links: ^5.0.10
  typescript: ">=4.8.4 <6.0.0"
