packages:
  - packages/*
catalog:
  "@fast-check/ava": ^2.0.2
  "@fortawesome/fontawesome-free": ^6.7.2
  "@parcel/packager-ts": 2.15.1
  "@parcel/transformer-sass": 2.15.1
  "@parcel/transformer-typescript-types": 2.15.1
  "@popperjs/core": ^2.11.8
  "@rollup/plugin-commonjs": ^28.0.3
  "@types/eslint": ^9.6.1
  "@types/node": ^22.15.18
  "@typescript-eslint/eslint-plugin": ^8.32.1
  "@typescript-eslint/parser": ^8.32.1
  ava: ^6.3.0
  bootstrap: ^5.3.6
  c8: ^10.1.3
  eslint: ^9.27.0
  eslint-config-love: ^120.0.0
  eslint-plugin-node: ^11.1.0
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-tsdoc: ^0.4.0
  fast-check: ^4.1.1
  fps-control: ^1.0.0
  gh-pages: ^6.3.0
  parcel: 2.15.1
  rollup: ^4.40.2
  tsimp: ^2.0.12
  typedoc: ^0.28.4
  typedoc-plugin-mdn-links: ^5.0.2
  typescript: ">=4.8.4 <5.8.0"
