packages:
  - packages/*
catalog:
  "@fast-check/ava": ^1.2.1
  "@fortawesome/fontawesome-free": ^6.7.2
  "@parcel/packager-ts": 2.13.3
  "@parcel/transformer-sass": 2.13.3
  "@parcel/transformer-typescript-types": 2.13.3
  "@popperjs/core": ^2.11.8
  "@rollup/plugin-commonjs": ^26.0.3
  "@types/eslint": ^8.56.12
  "@types/node": ^20.17.10
  "@typescript-eslint/eslint-plugin": ^7.18.0
  "@typescript-eslint/parser": ^7.18.0
  ava: ^6.2.0
  bootstrap: ^5.3.3
  c8: ^10.1.3
  eslint: ^8.57.1
  eslint-config-love: ^54.0.0
  eslint-plugin-node: ^11.1.0
  eslint-plugin-promise: ^6.6.0
  eslint-plugin-tsdoc: ^0.3.0
  fast-check: ^3.23.2
  fps-control: ^1.0.0
  gh-pages: ^6.2.0
  parcel: ^2.13.3
  rollup: ^4.28.1
  tsimp: ^2.0.12
  typedoc: ^0.26.11
  typedoc-plugin-mdn-links: ^3.3.8
  typescript: "4.6.x || 4.7.x || 4.8.x || 4.9.x || 5.0.x |
| 5.1.x || 5.2.x || 5.3.x || 5.4.x || 5.5.x || 5.6.x"
