version: 2.1
orbs:
  node: circleci/node@5
  coveralls: coveralls/coveralls@1
jobs:
  coverage:
    executor:
        name: node/default
        tag: "16.10"
    steps:
      - checkout
      - coveralls/upload
workflows:
  test:
    jobs:
      - node/test:
          version: '16.10'
          filters:
            branches:
              ignore: [ gh-pages ]
      - coverage:
          requires: [ node/test ]
