version: 2.1
orbs:
  node: circleci/node@5
  coveralls: coveralls/coveralls@1
jobs:
  coverage:
    executor:
        name: node/default
        tag: "16.10"
    steps:
      - checkout
      - when:
          condition:
            not:
              equal: [ gh-pages, << pipeline.git.branch >> ]
          steps:
            - node/install-packages
            - run: npm t
            - coveralls/upload
workflows:
  test:
    jobs:
      - coverage
