version: 2.1
orbs:
  node: circleci/node@5
  coveralls: coveralls/coveralls@1
jobs:
  coverage:
    executor:
        name: node/default
        tag: "16.10"
    steps:
      - checkout
      - when:
          condition:
            not:
              equal: [ gh-pages, << pipeline.git.branch >> ]
          steps:
            - restore_cache:
                name: Restore pnpm Package Cache
                keys:
                  - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
            - run:
                name: Install pnpm package manager
                command: |
                  corepack enable
                  corepack prepare pnpm@latest-9 --activate
                  pnpm config set store-dir .pnpm-store
            - run:
                name: Install Dependencies
                command: |
                  pnpm install
            - run: pnpm t
            - coveralls/upload
workflows:
  test:
    jobs:
      - coverage
